default = 0
timeout = 3
shutdown = true
firmware = true
backgrounds = ["\\EFI\\background\\example.jpeg"]
drivers = ["\\EFI\\drivers"]

[identity]
hostname = "Cat"
uuid = "11fba5dd-dee7-12e6-dad2-54755f0c5551"
mac = "A9:4C:42:5B:1A:B6"
token = "11fba5dd-dee7-12e6-dad2-54755f0c5551"

[network]
bind = "A9:4C:42:5B:1A:B6"
type = "dhcp"

[[entry]]
name = "Canicula Local Boot"
protocol = "canicula"
files = [
    { type = "kernel",  search = "esp",  file = "\\boot\\canicula-kernel", select = "latest" },
]

[[entry]]
name = "Linux Local Boot"
protocol = "linux"
files = [
    { type = "kernel",  search = "esp",  file = "\\boot\\vmlinuz-*", select = "latest" },
    { type = "initrd",  search = "esp",  file = "\\boot\\initrd.img-*", select = "latest" },
    { type = "initrd",  search = "esp",  file = "\\boot\\amd-ucode.img" },
    { type = "cmdline", search = "inline", content = "console=tty0 root=/dev/sda2 ro quiet" },
]

[[entry]]
name = "Canicula Network Boot"
# types: canicula and linux
protocol = "canicula"
files = [
    # type include: kernel, initrd and cmdline
    { type = "kernel",  search = "https", file = "https://os.canicula.org/boot/kernel" },
    { type = "cmdline", search = "https", file = "https://os.canicula.org/boot/cmdline" },
]

[[entry]]
name = "Linux Network Boot"
protocol = "linux"
identity = { hostname = "Cat", mac = "02:BB:CC:DD:EE:FF" }
files = [
    { type = "kernel",  search = "https", file = "https://os.canicula.org/boot/kernel" },
    { type = "cmdline", search = "https", file = "https://os.canicula.org/boot/cmdline" },
    { type = "initrd",  search = "https", file = "https://os.canicula.org/boot/initrd" },
]