[toolchain]
profile = "default"
channel = "nightly-2026-02-02"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
targets = [
    "x86_64-unknown-uefi",
    "aarch64-unknown-uefi",
    "riscv64gc-unknown-none-elf",
    "loongarch64-unknown-none",
]
